### PR TITLE
Fix blank node correlation (closes #795)

### LINKED ISSUE #795: @comunica/actor-init-sparql-rdfjs does not correlate blank nodes
#### Issue type:

- :bug: Bug

____
#### Description:

The actor implemented in `@comunica/actor-init-sparql-rdfjs` seems unable to correlate blank nodes when querying upon a RDF/JS source. 

The problem can be reproduced by running the test against the following manifest:

```sh
cd packages/actor-init-sparql-rdfjs
 ../../node_modules/.bin/rdf-test-suite-ldf spec/sparql-engine.js http://jacoscaz.com/manifest-ldf-tests/sparql-rdfjs/rdfjs-manifest.ttl -d 200000 -c ../../.rdf-test-suite-ldf-cache/
```

The manifest run a simple `SELECT * FROM { ?s ?p ?o}` query on the following quads:

```turtle
@prefix : <http://example.org/> .

:s1 :p1 _:b1 .
_:b1 :p2 :o2 .
```

The actor returns the following bindings:

```js
 Bindings:  [
  {
    "?s": {  "termType": "NamedNode",  "value": "http://example.org/s1" },
    "?p": { "termType": "NamedNode", "value": "http://example.org/p1" },
    "?o": {
      "termType": "BlankNode", "value": "bc_0_b4_b11",
      "skolemized": { "termType": "NamedNode", "value": "urn:comunica_skolem:source_0:b4_b1" }
    }
  },
  {
    "?s": {
      "termType": "BlankNode", "value": "bc_0_b4_b12",
      "skolemized": { "termType": "NamedNode", "value": "urn:comunica_skolem:source_0:b4_b1" }
    },
    "?p": { "termType": "NamedNode", "value": "http://example.org/p2" },
    "?o": { "termType": "NamedNode", "value": "http://example.org/o2" }
  }
]
```

While the skolemized versions of the two blank nodes are correlated, the labels themselves are not (but they should be!).

I stumbled into this issue while troubleshooting https://github.com/beautifulinteractions/node-quadstore/issues/134 and @rubensworks noted it might be related to https://github.com/comunica/comunica/issues/773 .
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.19.2 (dev)
| node                | v14.15.4
| npm                 | 7.4.1
| yarn                | 1.22.10
| Operating System    | darwin (Darwin 20.3.0)

### PR DESCRIPTION
**Pull request by jacoscaz**
This PR (~~which depends on https://github.com/comunica/sparqlee/pull/81~~ MERGED) fixes the blank node correlation issue raised in issue https://github.com/comunica/comunica/issues/795 (and may fix other similar issues). 

#### TODO

- [x] modify unit tests to match the new behavior of `packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts`
- [x] modify `ActorQueryOperation` tests to account for the `bnode` functions in expression contexts
- [x] add a test to verify blank node correlation
- [x] update to new version of `sparqlee` once https://github.com/comunica/sparqlee/pull/81 is merged and published to NPM
- [x] general cleanup and linting

### CODE REVIEW

File: packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts [hunk 1]
```diff
@@ -74,6 +75,9 @@ export class BindingsToQuadsIterator extends MultiTransformIterator<Bindings, RD
   public static localizeBlankNode(blankNodeCounter: number,
     term: RDF.Term): RDF.Term {
     if (term.termType === 'BlankNode') {
+      if (term instanceof BlankNodeBindingsScoped) {
```
Comment (rubensworks) [inline packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts:78]: Do we really need to preserve `BlankNodeBindingsScoped` in the context of construct queries?
AFAICS `BlankNodeBindingsScoped` is only really useful for bindings results, while we will always return quads here.

File: packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ export class ActorQueryOperationExtend extends ActorQueryOperationTypedMediated<
     );
 
     const extendKey = termToString(variable);
-    const config = { ...ActorQueryOperation.getExpressionContext(context, this.mediatorQueryOperation) };
+    const config = { ...ActorQueryOperation.getAsyncExpressionContext(context, this.mediatorQueryOperation) };
```
Comment (rubensworks) [inline packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts:36]: Is there a certain reason why this was changed?

We probably want the async context indeed, but I'm just wondering why it wasn't async in the first place.

File: packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts [hunk 3]
```diff
@@ -57,12 +58,15 @@ export class ActorQueryOperationProject extends ActorQueryOperationTypedMediated
     bindingsStream = bindingsStream.transform({
       map(bindings: Bindings) {
         blankNodeCounter++;
+        const scopedBlankNodesCache = new Map<string, RDF.BlankNode>();
         return <Bindings> bindings.map(term => {
-          if (term && term.termType === 'BlankNode') {
-            if (term instanceof BlankNodeScoped) {
-              return new BlankNodeScoped(`${term.value}${blankNodeCounter}`, term.skolemized);
```
Comment (rubensworks) [inline packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts:63]: Unless I'm missing something, we also need to keep `BlankNodeScoped`, right?

File: packages/bus-query-operation/lib/ActorQueryOperation.ts [hunk 4]
```diff
@@ -11,7 +12,9 @@ import type {
   Bindings,
   PatternBindings,
 } from '@comunica/types';
+import type * as RDF from 'rdf-js';
 import type { Algebra } from 'sparqlalgebrajs';
+import * as uuid from 'uuid';
```
Comment (rubensworks) [inline packages/bus-query-operation/lib/ActorQueryOperation.ts:17]: Can we use a simple counter to keep things more lightweight?

File: packages/data-factory/README.md [hunk 5]
```diff
@@ -18,3 +18,4 @@ $ yarn add @comunica/data-factory
 ## Exposed classes
 
 * [`BlankNodeScoped`](https://comunica.github.io/comunica/classes/data_factory.blanknodescoped-1.html): A blank node that is scoped to a certain source, and exposes a skolemized named node.
+* [`BlankNodeScoped`](https://comunica.github.io/comunica/classes/data_factory.blanknodescoped-1.html): A blank node that is scoped to a certain set of bindings.
```
Comment (rubensworks) [inline packages/data-factory/README.md:21]: `BlankNodeBindingsScoped`?

File: packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts (hunk 2 above)
Comment (jacoscaz) [reply packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts:36]: sparqlee's typings specify two different types of contexts, one the sync evaluator and another one for the async evaluator. The former one expects synchronous `bnode()` and `exists()` functions while the latter one expects asynchronous versions of those functions. The `exists()` function provided by comunica is always asynchronous and thus can only be included in the asynchronous context, hence I tried to use the asynchronous context as much as possible so as not to introduce breaking changes.

File: packages/bus-query-operation/lib/ActorQueryOperation.ts (hunk 4 above)
Comment (jacoscaz) [reply packages/bus-query-operation/lib/ActorQueryOperation.ts:17]: `uuid` is already a dependency of `sparqlee` so we're not introducing additional dependencies here. That said, this might change one day so +1 on this, will do.

File: packages/data-factory/README.md (hunk 5 above)
Comment (jacoscaz) [reply packages/data-factory/README.md:21]: Will do!

File: packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts (hunk 1 above)
Comment (jacoscaz) [reply packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts:78]: Mh... Right, I hadn't thought of that. Will do.

File: packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts (hunk 3 above)
Comment (jacoscaz) [reply packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts:63]: Why? A blank node scoped to a source is still a blank node that is not scoped to a single set of bindings. Modifying its label with a per-binding counter would break correlations, would it not?

File: packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts (hunk 2 above)
Comment (rubensworks) [reply packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts:36]: I think Comunica only makes use of the async context, or am I wrong there? If not, perhaps we can just have `getExpressionContext` always return an async context?

File: packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts (hunk 3 above)
Comment (rubensworks) [reply packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts:63]: We don't need to modify the label, we just need to ensure that we keep the skolemized term. Because we don't want to break cases like this that depend on these skolemized terms: https://github.com/solid/query-ldflex/issues/34

Comment (jacoscaz) [reply packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts:63]: Oooh my bad, I had misinterpreted the question. Will do!

File: packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts (hunk 2 above)
Comment (jacoscaz) [reply packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts:36]: That's what I thought, too, but then I found https://github.com/comunica/comunica/blob/7e77c0134b8354eb735ab2b805f8f6689f7c6b34/packages/actor-query-operation-group/lib/GroupsState.ts#L32  which uses the `SyncEvaluatorConfig` type.

Comment (rubensworks) [reply packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts:36]: Ah yes, aggregation happens sync. Then I guess there's no other way around this :-)

File: packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts (hunk 3 above)
Comment (jacoscaz) [reply packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts:63]: Doesn't the current version of the code already preserve `BlankNodeScoped`, though? All terms are returned as-is with the exception of `BlankNodeBindingsScoped` instances.

Comment (rubensworks) [reply packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts:63]: Ah yes, you're right, I didn't interpret the code correctly.
Then this change makes things even a bit cleaner :-)

File: packages/data-factory/README.md (hunk 5 above)
Comment (jacoscaz) [reply packages/data-factory/README.md]: Done!

File: packages/bus-query-operation/lib/ActorQueryOperation.ts (hunk 4 above)
Comment (jacoscaz) [reply packages/bus-query-operation/lib/ActorQueryOperation.ts]: Done!

File: packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts (hunk 1 above)
Comment (jacoscaz) [reply packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts]: Done!

File: packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts [hunk 6]
```diff
@@ -1,3 +1,4 @@
+import { BlankNodeBindingsScoped } from '@comunica/data-factory';
```
Comment (rubensworks) [inline packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts:1]: This can be removed now?

File: packages/data-factory/lib/BlankNodeBindingsScoped.ts [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+  public readonly termType: 'BlankNode' = 'BlankNode';
+  public readonly singleBindingsScope: true = true;
+  public readonly value: string;
+
+  public constructor(value: string) {
+    this.value = value;
+  }
+
+  public equals(other: RDF.Term | null | undefined): boolean {
+    // TODO: should we always return false given the nature of this class?
```
Comment (rubensworks) [inline packages/data-factory/lib/BlankNodeBindingsScoped.ts:16]: I would say no. I think the current implementation is fine.
Even if we always return false here, invoking `equals` from another bnode would still return true, which could cause more problems than we would fix.

File: packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts (hunk 6 above)
Comment (jacoscaz) [reply packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts]: Done!

File: packages/data-factory/lib/BlankNodeBindingsScoped.ts (hunk 7 above)
Comment (jacoscaz) [reply packages/data-factory/lib/BlankNodeBindingsScoped.ts]: Done!

**Comment by rubensworks** [comment]
Super, thanks for all your work on this!

**Comment by jacoscaz** [comment]
My pleasure! Do you think it'd be possible to publish a new version of Comunica soon-ish? Even a beta one, doesn't have to be an official release.
