### PR TITLE
resolve eager accept header boundary bug, fixes #534

### LINKED ISSUE #534: Wildcard accept header appending sometimes to eager
#### Issue type:

- :bug: Bug

____
#### Description:

The code in https://github.com/comunica/comunica/commit/53c7e7519f6125054ac5e80c79ca4b038f067a18 would cut off the last part of an accept header that perfectly fits into 127 characters, just to make room for the `*/*;q=0.1` it does not need.

Minor thing related to this:

might want to first convert toFixed before comparing to '1.00' because of rounding; and the regex might have `+` instead of `*`.

### PR DESCRIPTION
**Pull request by tbaccaer**
This pull request is supposed to fix the bug mentioned in issue 534.

### CODE REVIEW

**Review by rubensworks — APPROVED** [review]
Looks good to me, thanks!

@RubenVerborgh since you first noticed this issue, maybe you want to have a look at it as well?

**Review by RubenVerborgh — APPROVED** [review]
Looks good to me!

File: packages/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.ts [hunk 1]
```diff
@@ -135,20 +135,25 @@ export abstract class ActorRdfDereferenceHttpParseBase extends ActorRdfDereferen
...
+    // Take into account the ',' characters joining each type
+    const separatorLength = sortedMediaTypes.length - 1;
+    let partsLength = separatorLength;
     for (const entry of sortedMediaTypes) {
       const part = entry.mediaType + (entry.priority !== 1 ?
         `;q=${entry.priority.toFixed(3).replace(/0*$/u, '')}` :
         '');
       if (partsLength + part.length > maxLength) {
-        parts.push('*/*;q=0.1');
+        while (partsLength + wildcard.length > maxLength) {
```
Comment (RubenVerborgh) [inline packages/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.ts:151]: You could change this into a `do … while` since we know the condition will be true the first time.

Comment (tbaccaer) [reply packages/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.ts:151]: The condition is not necessarily true the first time. The while-condition covers the situation where there is enough space left to concatenate the wildcard, but not enough space left to concatenate a media type. Doing so anyway would result in an eager removal of a type, which would cause the original bug again.

 This scenario is covered by the first test, by the way:
Screenshot 2020-10-02 at 13 34 10

Comment (RubenVerborgh) [reply packages/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.ts:151]: My bad, thought the `if` and `while` had the same conditions. Good testing!
