### PR TITLE
Performance/optional

### LINKED ISSUE #496: Query with OPTIONAL gives invalid results
#### Issue type:

- :bug: Bug

____
#### Description:

The query (which you can find [here](http://query.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Fgeonames&query=PREFIX%20gn%3A%20%3Chttp%3A%2F%2Fwww.geonames.org%2Fontology%23%3E%0APREFIX%20w3pos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%0ASELECT%20%3FcountryCode%20%3Fpopulation%20WHERE%20%7B%0A%20%20%3Flocation%20gn%3Aname%20%22Belgium%22%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20gn%3AcountryCode%20%3FcountryCode%20.%0A%20%20OPTIONAL%20%7B%20%3Flocation%20gn%3Apopulation%20%3Fpopulation%20.%20%7D%0A%7D) does not give any result for the `?population`-binding. However, it is clear that some of the `?location`(s) do have a `population` defined (cfr. [this resource](http://data.linkeddatafragments.org/geonames?subject=http%3A%2F%2Fsws.geonames.org%2F5245314%2F)). 

As far as I know, I think some of the results should be provided of an (optional) `?population` binding.

____
#### Environment:

The jQuery-Widget.js environment

#### Crash log:

_None_

### LINKED ISSUE #583: Long execution time with OPTIONAL
#### Issue type:

- :snail: Performance issue

____
#### Description:

This query is fast:

```sparql
SELECT ?country ?capital ?caplat ?caplong WHERE {
  ?country a <http://dbpedia.org/ontology/Country>.
  ?country <http://dbpedia.org/ontology/capital> ?capital.
  ?capital <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?caplat;
           <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?caplong
}

```

But this closely related query is not:

```sparql
SELECT ?country ?capital ?caplat ?caplong WHERE {
  ?country a <http://dbpedia.org/ontology/Country>.
  OPTIONAL {
    ?country <http://dbpedia.org/ontology/capital> ?capital.
    ?capital <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?caplat;
             <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?caplong
  }
}
```

I takes 150 second before the first results start appearing. Furthermore, since it takes such a long time, I haven't been able to verify that it returns the correct results.

____

### PR DESCRIPTION
**Pull request by rubensworks**
Instead of resolving the left and right streams separately,
and joining the right with the left in an optional manner,
this actor functions in a left-deep manner.

Concretely, it will resolve the left stream,
and materialize+execute the right operation
with each binding.

This makes this actor significantly faster for larger streams.

Closes #583
Closes #496
Closes rubensworks/GraphQL-LD.js#13

Side-note: this PR shows the need for some kind of additional abstraction layer for left-deep joins (#427), as quite a bit of logic is duplicated from our left-deep-smallest BGP actor. Since this abstraction is not trivial, I did not make it part of this PR.

### CODE REVIEW

File: packages/actor-query-operation-leftjoin-left-deep/lib/ActorQueryOperationLeftJoinLeftDeep.ts [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+
+    // Create a left-deep stream with left and right.
+    const bindingsStream = ActorQueryOperationLeftJoinLeftDeep.createLeftDeepStream(left.bindingsStream, rightOperation,
+      async (operation: Algebra.Operation) => ActorQueryOperation.getSafeBindings(
+        await this.mediatorQueryOperation.mediate({ operation, context })).bindingsStream);
+
+    // Determine variables and metadata
+    const variables = ActorRdfJoin.joinVariables({ entries: [left, right] });
+    const metadata = () => Promise.all([left, right].map((entry) => entry.metadata()))
+      .then((metadatas) => metadatas.reduce((acc, val) => acc * val.totalItems, 1))
```
Comment (joachimvh) [inline packages/actor-query-operation-leftjoin-left-deep/lib/ActorQueryOperationLeftJoinLeftDeep.ts]: I would have just written `metadatas[0].totalItems * metadatas[1].totalItems` but I guess this also works :D
