### PR TITLE
Fix orderby bug with multiple comparators, Closes #598

### LINKED ISSUE #598: ORDER BY with multiple comparators takes only last comparator into account
#### Issue type:
- :bug: Bug

#### Description:
When a SPARQL query has an `ORDER BY` clause containing multiple comparators, it looks like only the last comparator is used when ordering.

#### Example 1
**input.ttl:**
```turtle
@prefix p: <http://example.org#> .

p:one
  p:name "Bosmans";
  p:givenName "Jos".

p:two
  p:name "Vermeulen";
  p:givenName "Jos".

p:three
  p:name "Vermeulen";
  p:givenName "Brecht".
```

**query.sparql:**
```sparql
PREFIX p: <http://example.org#>

SELECT ?name ?given
WHERE {
  ?person p:name ?name;
          p:givenName ?given .
}
ORDER BY ?given ?name
```

The query was executed as follows:
```
comunica-sparql-file input.ttl -f query.sparql
```

**Result:**
```json
[
{"?name":"\"Bosmans\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""}
]
```

**Expected result:**
```json
[
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""},
{"?name":"\"Bosmans\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""}
]
```

#### Example 2
Same input file, same query, only changed the order to: `ORDER BY ?name ?given`:

**Result:**
```json
[
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""},
{"?name":"\"Bosmans\"","?given":"\"Jos\""}
]
```

**Expected result:**
```json
[
{"?name":"\"Bosmans\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""}
]
```
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.10.0 
| node                | v10.16.3
| npm                 | 6.13.6
| Operating System    | linux (Linux 4.15.0-74-generic), Ubuntu 18.04

### PR DESCRIPTION
**Pull request by stephaniech97**

### CODE REVIEW

File: packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts [hunk 1]
```diff
@@ -41,10 +41,11 @@ export class ActorQueryOperationOrderBySparqlee extends ActorQueryOperationTyped
     const sparqleeConfig = { ...ActorQueryOperation.getExpressionContext(context) };
     let bindingsStream = output.bindingsStream;
 
-    for (let expr of pattern.expressions) {
+    //sorting backwards since the first one is the most important therefore should be ordered last.
+    for(let i = pattern.expressions.length-1; i >= 0 ;i--){
```
Comment (rubensworks) [inline packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts:45]: I'm surprised our linter does not complain about this, but we typically write our statements with spaces, like this:
```suggestion
    for (let i = pattern.expressions.length-1; i >= 0 ;i--) {
```
(also applies to if-statements and so on)

File: packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts [hunk 2]
```diff
@@ -69,7 +70,11 @@ export class ActorQueryOperationOrderBySparqlee extends ActorQueryOperationTyped
         if (!orderA || !orderB) {
           return 0;
         }
-        return orderA > orderB === isAscending ? 1 : -1;
+        if(isAscending){
```
Comment (rubensworks) [inline packages/actor-query-operation-orderby-sparqlee/lib/ActorQueryOperationOrderBySparqlee.ts:73]: Is this change really needed?
If I understand correctly, this defines an order when the two terms are equal.
But if they are equal, the return value should be `0`, right?

File: packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts [hunk 3]
```diff
@@ -146,3 +146,117 @@ describe('ActorQueryOperationOrderBySparqlee', () => {
     });
   });
 });
+
+describe('ActorQueryOperationOrderBySparqleeMultipleComparators', () => {
```
Comment (rubensworks) [inline packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts:150]:
```suggestion
describe('ActorQueryOperationOrderBySparqlee with multiple comparators', () => {
```
To avoid confusion with class names.

File: packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts [hunk 4]
```diff
@@ -146,3 +146,117 @@ describe('ActorQueryOperationOrderBySparqlee', () => {
...
+      const output = await actor.run(op);
+      const array = await arrayifyStream(ActorQueryOperation.getSafeBindings(output).bindingsStream);
+      expect(array).toMatchObject([
+        Bindings({ '?a': literal('Vermeulen'),'?b': literal('Ben') }),
+        Bindings({ '?a': literal("Bosmans"),'?b': literal('Jos') }),
+        Bindings({ '?a': literal('Vermeulen'),'?b': literal('Jos') }),
+      ]);
+    });
+
+    // Testing descending with multiple comparators
```
Comment (rubensworks) [inline packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts:225]: This comment _should_ not be needed. The essential information could be captured in the `it` label, so it's visible during test execution.

File: packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts [hunk 5]
```diff
@@ -146,3 +146,117 @@ describe('ActorQueryOperationOrderBySparqlee', () => {
...
+      const array = await arrayifyStream(ActorQueryOperation.getSafeBindings(output).bindingsStream);
+      expect(array).toMatchObject([
+        Bindings({ '?a': literal('Vermeulen'),'?b': literal('Jos') }),
+        Bindings({ '?a': literal("Bosmans"),'?b': literal('Jos')  }),
+        Bindings({ '?a': literal('Vermeulen'),'?b': literal('Ben') }),
+      ]);
+    });
+
+    // Testing with strlen operator
+    it('backup', async () => {
```
Comment (rubensworks) [inline packages/actor-query-operation-orderby-sparqlee/test/ActorQueryOperationOrderBySparqlee-test.ts:249]: This label should be a bit more descriptive :-)

**Comment by rubensworks** [comment]
Thanks @stephaniech97, great work!
