### PR TITLE
Fix tests

### LINKED ISSUE #300: Tests contain pointless checks
#### Issue type:

- :bug: Bug

____
#### Description:

In some query operation tests (e.g. FilterDirect, LeftJoinNestedLoop) checks like this ` expect(output.metadata()).toMatchObject(Promise.resolve({ totalItems: 3 }));` are made.

These however have no effect, and you can enter any number.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.4.1 (dev)
| node                | v8.12.0
| npm                 | 6.4.1
| yarn                | 1.10.1
| Operating System    | linux (Linux 4.15.0-34-generic)

### PR DESCRIPTION
**Pull request by simonvbrae**
closes #300 

- Change pointless tests to be useful.
- Fix a mistake in query-operation-leftjoin-nestedloop where the returned totalItems would always be Infinity.

### CODE REVIEW

File: packages/actor-query-operation-quadpattern/test/ActorQueryOperationQuadpattern-test.ts [hunk 1]
```diff
@@ -52,9 +52,11 @@ describe('ActorQueryOperationQuadpattern', () => {
     let mediator;
     let metadata;
     let metadataRaw;
+    let metadataContent;
 
     beforeEach(() => {
-      metadataRaw = Promise.resolve({ totalItems: 3 });
+      metadataContent = { totalitems: 3};
+      metadataRaw = Promise.resolve(metadataContent);
```
Comment (rubensworks) [inline packages/actor-query-operation-quadpattern/test/ActorQueryOperationQuadpattern-test.ts]: `metadataRaw` is not being used elsewhere anymore, I would merge it with the following line as follows: `() => Promise.resolve(metadataContent)`

**Comment by rubensworks** [comment]
Hmm, it looks like the test coverage has dropped...

Could you add a test that handles the missed line as reported in the comment above?

(you'll probably have to add a test with a metadata promise that rejects)

File: packages/actor-query-operation-leftjoin-nestedloop/test/ActorQueryOperationLeftJoinNestedLoop-test.ts [hunk 2]
```diff
@@ -59,7 +59,8 @@ describe('ActorQueryOperationLeftJoinNestedLoop', () => {
         left = !left;
         return Promise.resolve({
           bindingsStream: left ? bindingStreamLeft : bindingStreamRight,
-          metadata: () => Promise.resolve({ totalItems: 3 }),
+          metadata: () => arg.operation.hasOwnProperty("rejectMetadata") && arg.operation.rejectMetadata ?
```
Comment (rubensworks) [inline packages/actor-query-operation-leftjoin-nestedloop/test/ActorQueryOperationLeftJoinNestedLoop-test.ts]: Can be simplified to `arg.operation.rejectMetadata ? Promise.reject(new Error('fail')) : Promise.resolve({ totalItems: 3 })`

File: packages/actor-query-operation-leftjoin-nestedloop/test/ActorQueryOperationLeftJoinNestedLoop-test.ts [hunk 3]
```diff
@@ -117,6 +118,27 @@ describe('ActorQueryOperationLeftJoinNestedLoop', () => {
...
     });
 
+    it('should correctly handle rejecting promise in left and right', () => {
+      const op = { operation: { type: 'leftjoin', left: { rejectMetadata: true }, right: { rejectMetadata: true } } };
+      return actor.run(op).then(async (output: IActorQueryOperationOutputBindings) => {
+        expect(await output.metadata()).toMatchObject({ totalItems: Infinity });
+      });
+    });
+
+    it('should correctly handle rejecting promise in right', () => {
```
Comment (rubensworks) [inline packages/actor-query-operation-leftjoin-nestedloop/test/ActorQueryOperationLeftJoinNestedLoop-test.ts]: ' ... in left'

File: packages/actor-query-operation-leftjoin-nestedloop/test/ActorQueryOperationLeftJoinNestedLoop-test.ts [hunk 4]
```diff
@@ -117,6 +118,27 @@ describe('ActorQueryOperationLeftJoinNestedLoop', () => {
...
+      const op = { operation: { type: 'leftjoin', left: { rejectMetadata: true }, right: {} } };
+      return actor.run(op).then(async (output: IActorQueryOperationOutputBindings) => {
+        expect(await output.metadata()).toMatchObject({ totalItems: Infinity });
+      });
+    });
+
+    it('should correctly handle rejecting promise in left', () => {
```
Comment (rubensworks) [inline packages/actor-query-operation-leftjoin-nestedloop/test/ActorQueryOperationLeftJoinNestedLoop-test.ts]: ' ... in right'

**Comment by rubensworks** [comment]
Great work, thanks!
