### PR TITLE
fix: fix stats

### LINKED ISSUE #1354: Stats writer produces wrong totals
#### Issue type:

- :bug: Bug 

____
#### Description:

As of https://github.com/comunica/comunica/commit/0d7538cb154284af91a5027f89772bb3cc09f6fa, the stats writer produces wrong total times and result counts.

For example:
```
...
25809,16858.99227797985,45
25810,16859.01178896427,45
25811,16859.174924969673,45
25812,16859.219471931458,45
25813,16859.261418938637,45
25814,16859.264099001884,45
25815,16859.31561398506,45
25816,16859.519886016846,45
TOTAL,0.07797801494598389,21
```

Total time and request count is lower than those of the last result, which is impossible of course.

@jeswr, since this seems to be caused by your commit, could you look into fixing this? I suspect it will be a minor thing.

### PR DESCRIPTION
**Pull request by jeswr**
Closes #1354

### CODE REVIEW

File: packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts [hunk 1]
```diff
@@ -68,9 +68,13 @@ export class ActorQueryResultSerializeStats extends ActorQueryResultSerializeFix
...
     const startTime = this.now();
     let result = 1;
+
+    function* end(cb: () => string): Generator<string> {
+      yield cb();
+    }
     const stream = wrap(resultStream)
       .map(() => this.createStat(startTime, result++))
-      .append([ this.createFooter(startTime) ]);
+      .append(wrap(end(() => this.createFooter(startTime))));
```
Comment (rubensworks) [inline packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts:77]: Have you manually confirmed that this produces the expected output now?

Because I would expect that `wrap` creates an asynciterator with `autoStart: true`, and therefore eagerly creates the footer before it's actually needed.
But I could be incorrect of course.

Comment (jeswr) [reply packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts:77]: It should use the [`WrappingIterator`](https://github.com/RubenVerborgh/AsyncIterator/blob/266e5deb20df6d9033f01c137bcafee6721b1215/asynciterator.ts#L2223) which has no buffering and thus no autostart, instead pulling elements on-demand.

Will double check with a `stats` integration test.

Comment (rubensworks) [reply packages/actor-query-result-serialize-stats/lib/ActorQueryResultSerializeStats.ts:77]: Aha, then I will probably be wrong indeed.

**Comment by jeswr** [comment]
https://github.com/comunica/comunica/pull/1362/commits/89c7878b87be16310eab8a52c93c86027389f55f supercedes https://github.com/comunica/comunica/pull/1356 and removes the lines commented upon.

**Comment by rubensworks** [comment]
Thanks! :-)
